### ISSUE TITLE
Vortex fails to launch after install finishes.

### ISSUE THREAD

**Issue by Lejoni** [Furglitch/modorganizer2-linux-installer#21]
When I was prompted to manually disabling automatic updates in Vortex, vortex was launched just fine. I disabled the automatic update and then closed it again.
The install finished and I clicked the launch button and nothing happened.

If I try to launch vortex from lutris now, the Play button turns to a Stop button, and then after a few seconds back again to Play.

Log shows the following:
`Running /home/lejon/.local/share/lutris/runners/wine/lutris-5.2-x86_64/bin/wine /home/lejon/Games/vortex-mod-manager/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/Vortex.exe
Initial process has started with pid 1830
Game is considered started.

net.js:314
      err = this._handle.open(fd);
                         ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:314:26)
    at createWritableStdioStream (internal/process/stdio.js:179:18)
    at process.getStdout [as stdout] (internal/process/stdio.js:28:14)
    at Object.<anonymous> (electron/js2c/browser_init.js:5669:13)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:5824:30)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at electron/js2c/browser_init.js:84:18
    at electron/js2c/browser_init.js:87:10
    at NativeModule.compile (internal/bootstrap/loaders.js:287:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:222:8) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}
Game is considered exited.
Initial process has exited.
All monitored processes have exited.
Exit with returncode 256`

Don't understand why it would work during the install but not after.

**Comment by rockerbacon** [comment]
Since Vortex seems to be updating way too fast I will add instructions to disconnect from the internet at the prompt and reconnecting after disabling updates
