### ISSUE TITLE
Installer cancels install: "Operation canceled. Check the terminal for details"

### ISSUE THREAD

**Issue by CreativeGrey** [Furglitch/modorganizer2-linux-installer#308]
Not long after asking what folder I'd like to install MO2 in, it give me the above error and stops the install.

Below is the output from the terminal after running ./install.sh

> INFO: all dependencies met
Gtk-Message: 17:37:52.822: GtkDialog mapped without a transient parent. This is discouraged.
INFO: selected game 'skyrimspecialedition'
Gtk-Message: 17:37:55.742: GtkDialog mapped without a transient parent. This is discouraged.
INFO: found Steam in '/home/creativegrey/.local/share/Steam'
INFO: steam not found in '/home/creativegrey/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/creativegrey/.local/share/Steam'
Gtk-Message: 17:37:57.391: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 17:37:58.543: GtkDialog mapped without a transient parent. This is discouraged.
INFO: selected install directory '/home/creativegrey/Games/mod-organizer-2-skyrimspecialedition'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
Gtk-Message: 17:38:00.148: GtkDialog mapped without a transient parent. This is discouraged.
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
Gtk-Message: 17:38:06.444: GtkDialog mapped without a transient parent. This is discouraged.
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z'
INFO: downloading 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
Gtk-Message: 17:38:06.965: GtkDialog mapped without a transient parent. This is discouraged.
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
Gtk-Message: 17:38:22.412: GtkDialog mapped without a transient parent. This is discouraged.
INFO: using wget backend
INFO: fetching remote resource at 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
INFO: downloading 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' to '/tmp/mo2-linux-installer-downloads-cache/winetricks'
Gtk-Message: 17:38:26.587: GtkDialog mapped without a transient parent. This is discouraged.
INFO: using wget backend
INFO: fetching remote resource at 'https://skse.silverlock.org/beta/skse64_2_01_05.7z'
INFO: downloading 'https://skse.silverlock.org/beta/skse64_2_01_05.7z' to '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05.7z'
Gtk-Message: 17:38:27.025: GtkDialog mapped without a transient parent. This is discouraged.
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05.7z' to '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05'
Gtk-Message: 17:38:28.116: GtkDialog mapped without a transient parent. This is discouraged.
INFO: removing existing JDK installation in '/home/creativegrey/.local/share/Steam/steamapps/compatdata/489830/pfx/drive_c/java'
INFO: installing JDK in '/home/creativegrey/.local/share/Steam/steamapps/compatdata/489830/pfx/drive_c/java'
Gtk-Message: 17:38:28.189: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 17:38:28.843: GtkDialog mapped without a transient parent. This is discouraged.
INFO: skipping Mod Organizer 2 update
INFO: installing script extender in '/home/creativegrey/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/Data' into '/home/creativegrey/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/skse64_1_6_353.dll' into '/home/creativegrey/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/skse64_loader.exe' into '/home/creativegrey/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/skse64_steam_loader.dll' into '/home/creativegrey/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: installing nxm link broker in '/home/creativegrey/.local/share/modorganizer2'
INFO: installing nxm link handler in '/home/creativegrey/.local/share/applications/'
INFO: applying protontricks xaudio2_7=native
Traceback (most recent call last):
  File "/home/creativegrey/.local/bin/protontricks", line 8, in <module>
    sys.exit(main())
  File "/home/creativegrey/.local/pipx/venvs/protontricks/lib/python3.6/site-packages/protontricks/cli.py", line 177, in main
    steam_lib_paths = get_steam_lib_paths(steam_path)
  File "/home/creativegrey/.local/pipx/venvs/protontricks/lib/python3.6/site-packages/protontricks/steam.py", line 621, in get_steam_lib_paths
    library_folders = parse_library_folders(folders_vdf_path.read_text())
  File "/home/creativegrey/.local/pipx/venvs/protontricks/lib/python3.6/site-packages/protontricks/steam.py", line 605, in parse_library_folders
    Path(value) for key, value in vdf_data["LibraryFolders"].items()
KeyError: 'LibraryFolders'
Gtk-Message: 17:39:44.440: GtkDialog mapped without a transient parent. This is discouraged.
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'
Gtk-Message: 17:39:44.594: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by CreativeGrey** [comment]
Uninstalling every version of protontricks I could find and installing the pipx version seems to have worked
