### ISSUE TITLE
Doesn't install (SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates. ERROR: Protontricks did not find a valid prefix directory.  Stdout was:\n)

### ISSUE THREAD

**Issue by hrqmonteiro** [Furglitch/modorganizer2-linux-installer#751]
```
~/Downloads/mo2installer-5.0.3 ❯ ./install.sh 
INFO: all dependencies met

(zenity:289446): Gtk-WARNING **: 10:29:33.746: Unknown key gtk-modules in /home/hrq/.config/gtk-4.0/settings.ini
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/hrq/.local/share/Steam'
INFO: game found in '/home/hrq/.local/share/Steam'
INFO: steam not found in '/home/hrq/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.11.1', 'console_scripts', 'protontricks')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 339, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.
ERROR: Protontricks did not find a valid prefix directory.  Stdout was:\n
```

**Comment by rockerbacon** [comment]
That’s an issue with Protontricks
